import { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router'; import * as SecureStore from 'expo-secure-store'; import * as FileSystem from 'expo-file-system/legacy'; import * as Sharing from 'expo-sharing';
import { AppButton } from '../../components/AppButton'; import { AppCard } from '../../components/AppCard'; import { ErrorState } from '../../components/ErrorState'; import { LoadingScreen } from '../../components/LoadingScreen'; import { RouteTimeline } from '../../components/RouteTimeline';
import { API_BASE_URL } from '../../config/api'; import { useBooking, useBookingActions } from '../../hooks/usePassengerQueries'; import { COLORS, FONT_SIZE, RADIUS, SPACING } from '../../theme';

export default function BookingDetailScreen() {
  const { id = '' } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const query = useBooking(id); const actions = useBookingActions(); const [rating, setRating] = useState(5); const [comment, setComment] = useState(''); const [sharing, setSharing] = useState(false);
  if (query.isLoading) return <LoadingScreen />; if (query.isError || !query.data) return <ErrorState error={query.error} onRetry={() => query.refetch()} />; const booking = query.data;
  const download = async () => { setSharing(true); try { const token = await SecureStore.getItemAsync('accessToken'); const target = `${FileSystem.cacheDirectory}ShuttleMasr_Ticket_${id}.pdf`; const file = await FileSystem.downloadAsync(`${API_BASE_URL}/bookings/${id}/ticket`, target, { headers: { Authorization: `Bearer ${token}` } }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(file.uri, { mimeType: 'application/pdf', dialogTitle: 'Share ShuttleMasr ticket' }); } catch (e: any) { Alert.alert('Ticket unavailable', e.message); } finally { setSharing(false); } };
  const cancel = () => Alert.alert('Cancel booking?', 'Cancellation refunds follow the departure-time policy.', [{ text: 'Keep booking', style: 'cancel' }, { text: 'Cancel booking', style: 'destructive', onPress: () => actions.cancel.mutate(id, { onSuccess: () => void query.refetch(), onError: (e: any) => Alert.alert('Unable to cancel', e.response?.data?.message ?? e.message) }) }]);
  const rate = () => actions.rate.mutate({ id, rating, comment: comment.trim() || undefined }, { onSuccess: () => void query.refetch(), onError: (e: any) => Alert.alert('Unable to rate', e.response?.data?.message ?? e.message) });
  const canCancel = booking.status === 'CONFIRMED' && new Date(booking.trip.departureTime).getTime() > Date.now();
  const isLive = booking.trip.status === 'BOARDING' || booking.trip.status === 'IN_PROGRESS';
  const canTrack = isLive && (booking.status === 'CONFIRMED' || booking.status === 'COMPLETED');
  const outstanding = Number(booking.outstandingAmount ?? 0);
  const charges = booking.settledNoShowCharges ?? [];
  return <ScrollView style={styles.container} contentContainerStyle={styles.content}><AppButton label="Back" variant="ghost" onPress={() => router.back()} style={styles.back} /><Text style={styles.title}>{booking.trip.line.name}</Text><Text style={styles.status}>{booking.status} · Payment {booking.payment?.status ?? 'PENDING'}</Text>{canTrack ? <AppButton label="Track your ride" style={styles.action} onPress={() => router.push(`/tracking/${id}`)} /> : null}<AppCard><Text style={styles.heading}>{booking.pickupStop.nameEn} → {booking.dropoffStop.nameEn}</Text><Text style={styles.meta}>{new Date(booking.trip.departureTime).toLocaleString()}</Text><Text style={styles.meta}>{booking.seats} seat(s): {booking.bookingSeats.map((seat) => seat.seatNumber ?? '-').join(', ')}</Text><Text style={styles.fare}>{Number(booking.totalFare).toFixed(2)} EGP · {booking.payment?.method ?? booking.paymentMethod}</Text>{outstanding > 0 ? <View style={styles.outstandingBox}>{charges.length ? charges.map((c) => <Text key={c.id} style={styles.outstandingLine}>Outstanding from Trip #{c.tripId.slice(0, 8).toUpperCase()}: {Number(c.amount).toFixed(2)} EGP</Text>) : <Text style={styles.outstandingLine}>Outstanding balance: {outstanding.toFixed(2)} EGP</Text>}<Text style={styles.totalLine}>Total to pay: {(Number(booking.totalFare) + outstanding).toFixed(2)} EGP</Text></View> : null}</AppCard><AppCard><Text style={styles.heading}>Route</Text><RouteTimeline stops={booking.trip.line.lineStops ?? []} departureTime={booking.trip.departureTime} /></AppCard><AppButton label="Download / share ticket" loading={sharing} onPress={() => void download()} />{canCancel ? <AppButton label="Cancel booking" variant="outline" style={styles.action} onPress={cancel} /> : null}
    {booking.status === 'COMPLETED' && !booking.review ? <AppCard style={styles.rating}><Text style={styles.heading}>Rate your ride</Text><View style={styles.stars}>{[1, 2, 3, 4, 5].map((star) => <TouchableOpacity key={star} onPress={() => setRating(star)}><Text style={[styles.star, star > rating && styles.starOff]}>★</Text></TouchableOpacity>)}</View><TextInput style={styles.input} value={comment} onChangeText={setComment} placeholder="Optional comment" multiline maxLength={300} /><AppButton label="Submit rating" loading={actions.rate.isPending} onPress={rate} /></AppCard> : null}
  </ScrollView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.background }, content: { padding: SPACING.lg, paddingTop: 54, paddingBottom: 60 }, back: { alignSelf: 'flex-start' }, title: { fontSize: FONT_SIZE.xxxl, fontWeight: '900' }, status: { color: COLORS.primaryDark, fontWeight: '800', marginVertical: SPACING.md }, heading: { fontSize: FONT_SIZE.lg, fontWeight: '800' }, meta: { color: COLORS.textSecondary, marginTop: SPACING.sm }, fare: { fontSize: FONT_SIZE.xl, fontWeight: '900', marginTop: SPACING.lg }, action: { marginTop: SPACING.md }, outstandingBox: { marginTop: SPACING.md, borderTopWidth: 1, borderTopColor: COLORS.border, paddingTop: SPACING.sm }, outstandingLine: { color: COLORS.danger, fontWeight: '700', fontSize: FONT_SIZE.sm }, totalLine: { fontWeight: '900', marginTop: SPACING.xs }, rating: { marginTop: SPACING.lg }, stars: { flexDirection: 'row', marginVertical: SPACING.md }, star: { fontSize: 36, color: COLORS.primary }, starOff: { color: COLORS.border }, input: { minHeight: 80, borderWidth: 1, borderColor: COLORS.border, borderRadius: RADIUS.md, padding: SPACING.md, marginBottom: SPACING.md, textAlignVertical: 'top' } });
