import { useState } from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router'; import { useTranslation } from 'react-i18next';
import { AppCard } from '../../components/AppCard'; import { EmptyState } from '../../components/EmptyState'; import { ErrorState } from '../../components/ErrorState'; import { LoadingScreen } from '../../components/LoadingScreen';
import { COLORS, FONT_SIZE, RADIUS, SPACING } from '../../theme'; import { useBookings } from '../../hooks/usePassengerQueries'; import type { Booking } from '../../types/passenger';

type Filter = 'upcoming' | 'active' | 'completed' | 'cancelled';
export default function BookingsScreen() {
  const { t } = useTranslation(); const router = useRouter(); const query = useBookings(); const [filter, setFilter] = useState<Filter>('upcoming');
  if (query.isLoading) return <LoadingScreen />; if (query.isError) return <ErrorState error={query.error} onRetry={() => query.refetch()} />;
  const now = Date.now(); const matches = (booking: Booking) => filter === 'cancelled' ? ['CANCELLED', 'REFUNDED'].includes(booking.status) : filter === 'completed' ? booking.status === 'COMPLETED' : filter === 'active' ? ['BOARDING', 'IN_PROGRESS'].includes(booking.trip.status) : booking.status === 'CONFIRMED' && new Date(booking.trip.departureTime).getTime() > now && booking.trip.status === 'SCHEDULED';
  const bookings = (query.data ?? []).filter(matches);
  return <View style={styles.container}><Text style={styles.title}>{t('bookings.title')}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{(['upcoming', 'active', 'completed', 'cancelled'] as Filter[]).map((item) => <TouchableOpacity key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.activeFilter]}><Text style={[styles.filterText, filter === item && styles.activeText]}>{t(`bookings.${item}`)}</Text></TouchableOpacity>)}</ScrollView><ScrollView refreshControl={<RefreshControl refreshing={query.isFetching} onRefresh={() => query.refetch()} tintColor={COLORS.primary} />} contentContainerStyle={styles.list}>{bookings.length ? bookings.map((booking) => <AppCard key={booking.id} onPress={() => router.push(`/booking/${booking.id}`)}><View style={styles.top}><Text style={styles.line}>{booking.trip.line.name}</Text><Text style={styles.status}>{booking.status}</Text></View><Text style={styles.route}>{booking.pickupStop.nameEn} → {booking.dropoffStop.nameEn}</Text><Text style={styles.meta}>{new Date(booking.trip.departureTime).toLocaleString()} · {booking.seats} seat{booking.seats > 1 ? 's' : ''}</Text><Text style={styles.fare}>{Number(booking.totalFare).toFixed(2)} EGP · {booking.payment?.method ?? booking.paymentMethod}</Text></AppCard>) : <EmptyState title={t('bookings.empty')} icon="BK" />}</ScrollView></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.background }, title: { fontSize: FONT_SIZE.xxxl, fontWeight: '900', paddingHorizontal: SPACING.lg, paddingTop: 60 }, filters: { padding: SPACING.lg, gap: SPACING.sm }, filter: { paddingVertical: SPACING.sm, paddingHorizontal: SPACING.lg, borderRadius: RADIUS.full, backgroundColor: COLORS.card, borderWidth: 1, borderColor: COLORS.border }, activeFilter: { backgroundColor: COLORS.primary, borderColor: COLORS.primary }, filterText: { color: COLORS.textSecondary, fontWeight: '700' }, activeText: { color: COLORS.text }, list: { paddingHorizontal: SPACING.lg, paddingBottom: 120, flexGrow: 1 }, top: { flexDirection: 'row', justifyContent: 'space-between' }, line: { fontSize: FONT_SIZE.lg, fontWeight: '800' }, status: { color: COLORS.primaryDark, fontWeight: '800', fontSize: FONT_SIZE.sm }, route: { marginTop: SPACING.sm, fontWeight: '600' }, meta: { marginTop: SPACING.sm, color: COLORS.textSecondary }, fare: { marginTop: SPACING.sm, color: COLORS.text, fontWeight: '700' } });
