import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import MapView, { Marker, Region } from 'react-native-maps';
import * as Location from 'expo-location';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { AppButton } from '../../components/AppButton'; import { AppCard } from '../../components/AppCard';
import { COLORS, FONT_SIZE, RADIUS, SPACING } from '../../theme'; import { searchTrips } from '../../services/passengerService';
import type { Coordinates, SearchResult, Trip } from '../../types/passenger';

const CAIRO = { latitude: 30.0444, longitude: 31.2357 }; const DESTINATION = { latitude: 30.0131, longitude: 31.2089 }; const POINTS_KEY = 'passenger_search_points';
export default function HomeScreen() {
  const { t } = useTranslation(); const router = useRouter(); const map = useRef<MapView>(null);
  const [origin, setOrigin] = useState<Coordinates>(CAIRO); const [destination, setDestination] = useState<Coordinates>(DESTINATION); const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const [results, setResults] = useState<SearchResult[]>([]); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  const locate = async () => { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') return setMessage(t('home.permission')); const current = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); const point = { latitude: current.coords.latitude, longitude: current.coords.longitude }; setOrigin(point); map.current?.animateToRegion({ ...point, latitudeDelta: 0.12, longitudeDelta: 0.12 }); };
  useEffect(() => { void (async () => { const saved = await AsyncStorage.getItem(POINTS_KEY); if (saved) { const points = JSON.parse(saved); setOrigin(points.origin); setDestination(points.destination); } else await locate(); })(); }, []);
  const search = async () => { setLoading(true); setMessage(''); try { const data = await searchTrips(origin, destination, date); setResults(data); await AsyncStorage.setItem(POINTS_KEY, JSON.stringify({ origin, destination })); if (!data.length) setMessage(t('home.noTrips')); } catch (e: any) { setMessage(e.response?.data?.message ?? 'Unable to search trips'); } finally { setLoading(false); } };
  const openTrip = (result: SearchResult, trip: Trip) => router.push({ pathname: '/trip/[id]', params: { id: trip.id, result: JSON.stringify(result), trip: JSON.stringify(trip) } });
  const region: Region = { ...origin, latitudeDelta: 0.18, longitudeDelta: 0.18 };
  return <View style={styles.container}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{t('home.title')}</Text><View style={styles.mapWrap}><MapView ref={map} style={styles.map} initialRegion={region}><Marker coordinate={origin} draggable onDragEnd={(e) => setOrigin(e.nativeEvent.coordinate)} pinColor={COLORS.success} title={t('home.origin')} /><Marker coordinate={destination} draggable onDragEnd={(e) => setDestination(e.nativeEvent.coordinate)} pinColor={COLORS.danger} title={t('home.destination')} /></MapView><TouchableOpacity style={styles.locate} onPress={() => void locate()}><Ionicons name="locate" size={22} color={COLORS.text} /></TouchableOpacity></View>
    <View style={styles.points}><View><Text style={styles.pointLabel}>{t('home.origin')}</Text><Text style={styles.coords}>{origin.latitude.toFixed(4)}, {origin.longitude.toFixed(4)}</Text></View><View><Text style={styles.pointLabel}>{t('home.destination')}</Text><Text style={styles.coords}>{destination.latitude.toFixed(4)}, {destination.longitude.toFixed(4)}</Text></View></View>
    <View style={styles.dateRow}><Text style={styles.pointLabel}>Travel date</Text><TouchableOpacity onPress={() => { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() + 1); setDate(next.toISOString().slice(0, 10)); }}><Text style={styles.date}>{date}  +1 day</Text></TouchableOpacity></View><AppButton label={t('home.search')} loading={loading} onPress={() => void search()} />{message ? <Text style={styles.message}>{message}</Text> : null}
    {results.flatMap((result) => result.trips.map((trip) => <AppCard key={trip.id} onPress={() => openTrip(result, trip)}><View style={styles.resultTop}><Text style={styles.lineName}>{result.line.name}</Text><Text style={styles.price}>{Number(trip.pricePerSeat).toFixed(0)} EGP</Text></View><Text style={styles.route}>{result.pickupLineStop.stop.nameEn}  →  {result.dropoffLineStop.stop.nameEn}</Text><Text style={styles.meta}>{new Date(trip.departureTime).toLocaleString()} · {trip.availableSeats} seats</Text><Text style={styles.walk}>Walk {Math.round(result.pickupDistanceMeters)}m to pickup · {Math.round(result.dropoffDistanceMeters)}m from drop-off</Text></AppCard>))}
  </ScrollView>{loading ? <ActivityIndicator style={styles.busy} color={COLORS.primary} /> : null}</View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.background }, content: { padding: SPACING.lg, paddingTop: 60, paddingBottom: 120 }, title: { fontSize: FONT_SIZE.xxxl, fontWeight: '900', marginBottom: SPACING.lg }, mapWrap: { height: 290, borderRadius: RADIUS.xl, overflow: 'hidden', marginBottom: SPACING.md }, map: { flex: 1 }, locate: { position: 'absolute', right: 12, bottom: 12, width: 44, height: 44, borderRadius: 22, backgroundColor: COLORS.card, alignItems: 'center', justifyContent: 'center' }, points: { flexDirection: 'row', gap: SPACING.md, marginBottom: SPACING.md }, pointLabel: { fontWeight: '800', color: COLORS.text }, coords: { fontSize: FONT_SIZE.xs, color: COLORS.textSecondary, marginTop: 3 }, dateRow: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: COLORS.card, borderRadius: RADIUS.md, padding: SPACING.md, marginBottom: SPACING.md }, date: { color: COLORS.primaryDark, fontWeight: '700' }, message: { textAlign: 'center', color: COLORS.textSecondary, marginVertical: SPACING.lg }, resultTop: { flexDirection: 'row', justifyContent: 'space-between' }, lineName: { fontSize: FONT_SIZE.lg, fontWeight: '800' }, price: { fontWeight: '800', color: COLORS.primaryDark }, route: { marginTop: SPACING.sm, fontWeight: '600' }, meta: { color: COLORS.textSecondary, marginTop: SPACING.sm }, walk: { color: COLORS.textMuted, fontSize: FONT_SIZE.sm, marginTop: SPACING.sm }, busy: { position: 'absolute', top: '50%', left: '50%' } });
