import { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { AppButton } from '../../components/AppButton'; import { AppCard } from '../../components/AppCard'; import { RouteTimeline } from '../../components/RouteTimeline';
import { COLORS, FONT_SIZE, RADIUS, SPACING } from '../../theme'; import { useBookingActions } from '../../hooks/usePassengerQueries';
import type { PaymentMethod, SearchResult, Trip } from '../../types/passenger';

export default function TripDetailScreen() {
  const params = useLocalSearchParams<{ result: string; trip: string }>(); const router = useRouter();
  const result = JSON.parse(params.result) as SearchResult; const trip = JSON.parse(params.trip) as Trip;
  const [seats, setSeats] = useState(1); const [promoCode, setPromoCode] = useState(''); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('WALLET'); const { create } = useBookingActions();
  const canBook = Boolean(trip.isBookable) && trip.status === 'SCHEDULED' && trip.availableSeats >= seats && new Date(trip.departureTime).getTime() > Date.now() + 10 * 60_000;
  const submit = () => {
    if (!canBook) {
      Alert.alert('Booking unavailable', 'This trip is no longer inside the booking window. Please choose a later departure.');
      return;
    }
    create.mutate({ tripId: trip.id, pickupStopId: result.pickupLineStop.stop.id, dropoffStopId: result.dropoffLineStop.stop.id, seats, promoCode: promoCode.trim() || undefined, paymentMethod }, { onSuccess: (booking) => router.replace(`/booking/${booking.id}`), onError: (e: any) => Alert.alert('Booking failed', e.response?.data?.message ?? e.message) });
  };
  return <ScrollView style={styles.container} contentContainerStyle={styles.content}><AppButton label="Back" variant="ghost" onPress={() => router.back()} style={styles.back} /><Text style={styles.title}>{result.line.name}</Text><Text style={styles.subtitle}>{new Date(trip.departureTime).toLocaleString()}</Text>
    <AppCard><Text style={styles.section}>Route</Text><RouteTimeline stops={result.line.lineStops} /></AppCard>
    <AppCard><Text style={styles.section}>Trip details</Text><Text style={styles.row}>{result.pickupLineStop.stop.nameEn} → {result.dropoffLineStop.stop.nameEn}</Text><Text style={styles.meta}>Driver: {result.line.driver?.user?.name ?? 'To be assigned'}</Text><Text style={styles.meta}>Vehicle: {result.line.driver?.vehicle?.model ?? result.line.driver?.vehicle?.type ?? 'To be assigned'} · {result.line.driver?.vehicle?.plateNumber ?? ''}</Text><Text style={styles.meta}>{trip.availableSeats} seats available</Text></AppCard>
    <AppCard><Text style={styles.section}>Seats</Text><View style={styles.selector}>{[1, 2, 3].map((count) => <TouchableOpacity key={count} disabled={count > trip.availableSeats} onPress={() => setSeats(count)} style={[styles.choice, seats === count && styles.selected, count > trip.availableSeats && styles.disabledChoice]}><Text style={styles.choiceText}>{count}</Text></TouchableOpacity>)}</View><Text style={styles.section}>Deferred payment</Text><View style={styles.selector}>{(['WALLET', 'CASH'] as PaymentMethod[]).map((method) => <TouchableOpacity key={method} onPress={() => setPaymentMethod(method)} style={[styles.method, paymentMethod === method && styles.selected]}><Text style={styles.choiceText}>{method === 'WALLET' ? 'Wallet after trip' : 'Cash on board'}</Text></TouchableOpacity>)}</View><TextInput style={styles.input} value={promoCode} onChangeText={setPromoCode} placeholder="Promo code (optional)" autoCapitalize="characters" /><View style={styles.total}><Text style={styles.section}>Estimated total</Text><Text style={styles.price}>{(Number(trip.pricePerSeat) * seats).toFixed(2)} EGP</Text></View><Text style={styles.note}>{canBook ? 'Payment is collected after the ride. Promo discounts are applied by the server.' : 'Booking window is closed for this departure. Please choose a later trip.'}</Text><AppButton label="Confirm booking" loading={create.isPending} disabled={!canBook} onPress={submit} /></AppCard>
  </ScrollView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.background }, content: { padding: SPACING.lg, paddingTop: 54, paddingBottom: 50 }, back: { alignSelf: 'flex-start' }, title: { fontSize: FONT_SIZE.xxxl, fontWeight: '900' }, subtitle: { color: COLORS.textSecondary, marginTop: SPACING.xs, marginBottom: SPACING.lg }, section: { fontSize: FONT_SIZE.lg, fontWeight: '800', marginBottom: SPACING.md }, row: { fontWeight: '700' }, meta: { color: COLORS.textSecondary, marginTop: SPACING.sm }, selector: { flexDirection: 'row', gap: SPACING.sm, marginBottom: SPACING.lg }, choice: { width: 48, height: 44, borderRadius: RADIUS.full, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center', justifyContent: 'center' }, disabledChoice: { opacity: 0.35 }, method: { flex: 1, minHeight: 48, borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center', justifyContent: 'center', padding: SPACING.sm }, selected: { borderColor: COLORS.primaryDark, backgroundColor: COLORS.primaryLight }, choiceText: { fontWeight: '700' }, input: { borderWidth: 1, borderColor: COLORS.border, borderRadius: RADIUS.md, padding: SPACING.md, marginBottom: SPACING.lg }, total: { flexDirection: 'row', justifyContent: 'space-between' }, price: { fontSize: FONT_SIZE.xl, fontWeight: '900', color: COLORS.primaryDark }, note: { color: COLORS.textSecondary, fontSize: FONT_SIZE.sm, marginBottom: SPACING.lg } });
