import { RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router'; import { useTranslation } from 'react-i18next';
import { AppCard } from '../../components/AppCard'; import { EmptyState } from '../../components/EmptyState'; import { ErrorState } from '../../components/ErrorState'; import { LoadingScreen } from '../../components/LoadingScreen';
import { useNotificationActions, useNotifications } from '../../hooks/usePassengerQueries'; import { COLORS, FONT_SIZE, SPACING } from '../../theme';

export default function NotificationsScreen() {
  const { t, i18n } = useTranslation(); const router = useRouter(); const query = useNotifications(); const actions = useNotificationActions();
  if (query.isLoading) return <LoadingScreen />; if (query.isError) return <ErrorState error={query.error} onRetry={() => query.refetch()} />; const items = query.data ?? [];
  const open = (item: typeof items[number]) => { if (!item.isRead) actions.markRead.mutate(item.id); if (item.payload?.bookingId) router.push(`/booking/${item.payload.bookingId}`); };
  return <View style={styles.container}><View style={styles.header}><Text style={styles.title}>{t('tabs.notifications')}</Text>{items.some((item) => !item.isRead) ? <TouchableOpacity onPress={() => actions.markAllRead.mutate()}><Text style={styles.mark}>Mark all read</Text></TouchableOpacity> : null}</View><ScrollView refreshControl={<RefreshControl refreshing={query.isFetching} onRefresh={() => query.refetch()} tintColor={COLORS.primary} />} contentContainerStyle={styles.content}>{items.length ? items.map((item) => <AppCard key={item.id} onPress={() => open(item)} active={!item.isRead}><View style={styles.row}><View style={[styles.dot, item.isRead && styles.read]} /><View style={styles.text}><Text style={styles.itemTitle}>{i18n.language === 'ar' && item.titleAr ? item.titleAr : item.title}</Text><Text style={styles.body}>{i18n.language === 'ar' && item.bodyAr ? item.bodyAr : item.body}</Text><Text style={styles.time}>{new Date(item.createdAt).toLocaleString()}</Text></View></View></AppCard>) : <EmptyState title="All caught up" message="Booking updates and trip reminders appear here." icon="NT" />}</ScrollView></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.background }, header: { paddingTop: 60, paddingHorizontal: SPACING.lg, paddingBottom: SPACING.md, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontSize: FONT_SIZE.xxxl, fontWeight: '900' }, mark: { color: COLORS.primaryDark, fontWeight: '800' }, content: { padding: SPACING.lg, paddingBottom: 120, flexGrow: 1 }, row: { flexDirection: 'row', gap: SPACING.md }, dot: { width: 10, height: 10, borderRadius: 5, backgroundColor: COLORS.primary, marginTop: 6 }, read: { backgroundColor: COLORS.border }, text: { flex: 1 }, itemTitle: { fontSize: FONT_SIZE.lg, fontWeight: '800' }, body: { color: COLORS.textSecondary, marginTop: SPACING.xs, lineHeight: 21 }, time: { color: COLORS.textMuted, fontSize: FONT_SIZE.xs, marginTop: SPACING.sm } });
