import { useState } from 'react';
import { Alert, RefreshControl, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { AppButton } from '../../components/AppButton'; import { AppCard } from '../../components/AppCard';
import { changeLanguage } from '../../i18n'; import { useWalletTransactions } from '../../hooks/usePassengerQueries'; import { updateProfile } from '../../services/passengerService'; import { disablePushNotifications, enablePushNotifications } from '../../services/pushNotifications'; import { useAuthStore } from '../../stores/authStore'; import { COLORS, FONT_SIZE, RADIUS, SPACING } from '../../theme';

export default function ProfileScreen() {
  const { t, i18n } = useTranslation(); const { user, updateUser, refreshProfile, logout } = useAuthStore(); const wallet = useWalletTransactions(); const [name, setName] = useState(user?.name ?? ''); const [email, setEmail] = useState(user?.email ?? ''); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [pushEnabled, setPushEnabled] = useState(true);
  const save = async () => { setSaving(true); try { const updated = await updateProfile({ name: name.trim(), email: email.trim() || undefined }); updateUser(updated); setEditing(false); } catch (e: any) { Alert.alert('Could not save', e.response?.data?.message ?? e.message); } finally { setSaving(false); } };
  const togglePush = async (enabled: boolean) => { setPushEnabled(enabled); if (enabled) await enablePushNotifications(); else await disablePushNotifications(); };
  const signOut = () => Alert.alert('Log out?', '', [{ text: 'Cancel', style: 'cancel' }, { text: 'Log out', style: 'destructive', onPress: async () => { await disablePushNotifications(); await logout(); } }]);
  return <ScrollView style={styles.container} refreshControl={<RefreshControl refreshing={false} onRefresh={() => { void refreshProfile(); void wallet.refetch(); }} tintColor={COLORS.primary} />} contentContainerStyle={styles.content}><Text style={styles.title}>{t('profile.title')}</Text><AppCard><Text style={styles.heading}>{t('profile.personal')}</Text>{editing ? <><TextInput style={styles.input} value={name} onChangeText={setName} placeholder="Name" /><TextInput style={styles.input} value={email} onChangeText={setEmail} placeholder="Email" keyboardType="email-address" autoCapitalize="none" /><AppButton label={t('common.save')} loading={saving} onPress={() => void save()} /></> : <><Text style={styles.name}>{user?.name}</Text><Text style={styles.meta}>{user?.phone}</Text><Text style={styles.meta}>{user?.email || 'No email added'}</Text><AppButton style={styles.action} label="Edit profile" variant="outline" onPress={() => setEditing(true)} /></>}</AppCard>
    <AppCard><Text style={styles.heading}>{t('profile.wallet')}</Text><View style={styles.balanceRow}><View><Text style={styles.label}>{t('profile.balance')}</Text><Text style={styles.balance}>{Number(user?.walletBalance ?? 0).toFixed(2)} EGP</Text></View><View><Text style={styles.label}>{t('profile.outstanding')}</Text><Text style={[styles.balance, Number(user?.outstandingBalance ?? 0) > 0 && styles.danger]}>{Number(user?.outstandingBalance ?? 0).toFixed(2)} EGP</Text></View></View><Text style={styles.subheading}>{t('profile.transactions')}</Text>{(wallet.data ?? []).slice(0, 8).map((item) => <View key={item.id} style={styles.transaction}><View style={styles.transactionText}><Text style={styles.transactionTitle}>{item.description || item.type}</Text><Text style={styles.time}>{new Date(item.createdAt).toLocaleString()}</Text></View><Text style={item.type === 'CREDIT' ? styles.credit : styles.debit}>{item.type === 'CREDIT' ? '+' : '-'}{Number(item.amount).toFixed(2)}</Text></View>)}</AppCard>
    <AppCard><View style={styles.setting}><Text style={styles.heading}>{t('profile.notifications')}</Text><Switch value={pushEnabled} onValueChange={(value) => void togglePush(value)} trackColor={{ true: COLORS.primary }} /></View><Text style={styles.label}>{t('profile.language')}</Text><View style={styles.language}><AppButton label="English" variant={i18n.language === 'en' ? 'primary' : 'outline'} onPress={() => void changeLanguage('en')} /><AppButton label="العربية" variant={i18n.language === 'ar' ? 'primary' : 'outline'} onPress={() => void changeLanguage('ar')} /></View></AppCard><AppButton label={t('profile.logout')} variant="outline" onPress={signOut} />
  </ScrollView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.background }, content: { padding: SPACING.lg, paddingTop: 60, paddingBottom: 120 }, title: { fontSize: FONT_SIZE.xxxl, fontWeight: '900', marginBottom: SPACING.lg }, heading: { fontSize: FONT_SIZE.lg, fontWeight: '800' }, subheading: { fontWeight: '800', marginTop: SPACING.xl, marginBottom: SPACING.sm }, name: { fontSize: FONT_SIZE.xl, fontWeight: '800', marginTop: SPACING.md }, meta: { color: COLORS.textSecondary, marginTop: SPACING.xs }, action: { marginTop: SPACING.lg }, input: { borderWidth: 1, borderColor: COLORS.border, borderRadius: RADIUS.md, padding: SPACING.md, marginTop: SPACING.md }, balanceRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: SPACING.lg }, label: { color: COLORS.textSecondary, fontSize: FONT_SIZE.sm, fontWeight: '700' }, balance: { fontSize: FONT_SIZE.xl, fontWeight: '900', marginTop: SPACING.xs }, danger: { color: COLORS.danger }, transaction: { flexDirection: 'row', alignItems: 'center', paddingVertical: SPACING.md, borderTopWidth: 1, borderTopColor: COLORS.borderLight }, transactionText: { flex: 1 }, transactionTitle: { fontWeight: '700' }, time: { color: COLORS.textMuted, fontSize: FONT_SIZE.xs, marginTop: 2 }, credit: { color: COLORS.success, fontWeight: '800' }, debit: { color: COLORS.danger, fontWeight: '800' }, setting: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: SPACING.lg }, language: { flexDirection: 'row', gap: SPACING.sm, marginTop: SPACING.sm } });
